### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by avgorny** [BartoszBaczek/WorkshopRequestsManager#11]
Cześć,
Jak dodać część do requesta??
Bo nie wiem czy mi tabela nie wypisuje części czy request nie posiada tej listy,,,
raczej chyba to drugie bo totalPrize zwraca 0. Możesz coś z tym zrobić?

**Comment by bbonczek** [comment]
dodawanie requestow jeszcze nie jest gotowe ;) skoncze to dzisiaj, albo jutro.

**Comment by bbonczek** [comment]
wszystko dziala
