### ISSUE TITLE
Możesz dodać kilka przykładowych narzędzi do bazy?

### ISSUE THREAD

**Issue by bbonczek** [BartoszBaczek/WorkshopRequestsManager#12]

**Comment by McMorn** [comment]
Narzędzi tzn?

**Comment by bbonczek** [comment]
Partów*.

**Comment by KrystekKlein** [comment]
powinna byc masa...

**Comment by McMorn** [comment]
Bart, w tabeli Parts jest jakieś 1600 rekordów.
![image](https://cloud.githubusercontent.com/assets/11898940/12723143/7a9ee700-c908-11e5-9cf7-335af56188e1.png)
