### ISSUE TITLE
Aktualizacja zlecenia

### ISSUE THREAD

**Issue by KrystekKlein** [BartoszBaczek/WorkshopRequestsManager#5]
Proszę dodaj metodę która umożliwi update całego rekordu, wywoływanie pojedyńczych będzie mało efektywne bo program będzie musiał n razy łączyć się z baza żeby zaktualizować jeden element

**Comment by McMorn** [comment]
Postaram się to zrobić dzisiaj wieczorem. Jeśli możesz to doprecyzuj co dokładnie chcesz, aby było update'owane razem : Marka i Model; Marka, Model, Właściciel, Marka, Model, Właściciel, Komentarz... Pamiętaj, że dla metody, która update'uje wszystkie kolumny dla każdej, której nie chcesz zmienić musisz podać obecną wartość, w innym wypadku w bazie pojawią się nieprawidłowe dane.

**Comment by KrystekKlein** [comment]
Masz raję ale ja będę od nich dostawał zawsze pełny rekord(obiekt) te pojedyncze zostaw bo powinny byc przydatne ale tak która wszystk tzn. marka, model, wlasciciel, komentarz, no i cos podobnego do listy w czesciach z tym ze musi byc dopisz do listy nie aktualizacja rekordu, trzeba by rozwazyc tez temat ze moze byc kilka tych samyh czesci ale to juz z bartem trzeba obgadac.
