### ISSUE TITLE
Button do generowania PDF

### ISSUE THREAD

**Issue by avgorny** [BartoszBaczek/WorkshopRequestsManager#7]
Bartek proszę dodaj button do generowania pdf'a,
dodaj do niego metodę z klasy PDF :  PDFGenerate(Request request)
powina ona dostać cały obiekt tej klasy. Chciałbym zacząc testować to generowanie pdf.

**Comment by bbonczek** [comment]
Dodam dzisiaj

**Comment by bbonczek** [comment]
dodano
