### ISSUE TITLE
W Interfejsie IRequestDatabaseAdapter brakuje metody getArchivizedRequests i getActiveRequests

### ISSUE THREAD

**Issue by bbonczek** [BartoszBaczek/WorkshopRequestsManager#8]
Request w sqlu jest opisany dodatkowo przez boola isArchovized. Takiego pola brakuje w klasie Request którą mamy w modelu. Trzeba dopisać do requesta pole _bool Archivized_ i dopisac metody umozliwiajace wyciagniecie archiwizowane/aktywne requesty

**Comment by KrystekKlein** [comment]
Ja dodałem tylko pole do obiektu i masz liste nie możesz tego po Linq wysortować?

**Comment by bbonczek** [comment]
mogę :D
